services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: csn
      POSTGRES_PASSWORD: csn_pass
      POSTGRES_DB: csn_notification
    ports:
      - "5444:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql/data

volumes:
  notification_pgdata:
